# Generated by Django 5.0 on 2023-12-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesurement_list',
            name='Comment',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
