# Generated by Django 5.0 on 2023-12-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_mesurement_list_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesured_places',
            fields=[
                ('ID', models.SlugField(default='', editable=False, primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField(auto_now=True)),
                ('Name', models.CharField(max_length=50)),
                ('Required_ph', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='permission_set',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='mesurement_list',
            name='ID',
            field=models.SlugField(default='', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('ID', models.SlugField(default='', editable=False, primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField(auto_now=True)),
                ('Name', models.CharField(max_length=50)),
                ('Permission', models.ManyToManyField(to='user_side.permission_set')),
            ],
        ),
        migrations.CreateModel(
            name='mesurement_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Time', models.DateTimeField(auto_now=True)),
                ('Finished', models.BooleanField(default=False)),
                ('End_Time', models.DateTimeField(editable=False)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.mesurement_list')),
                ('Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.mesured_places')),
                ('Persone', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.user')),
            ],
        ),
        migrations.AddField(
            model_name='mesured_places',
            name='Persone',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.user'),
        ),
    ]
