# Generated by Django 5.0 on 2023-12-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_rename_mesured_places_mesured_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurement_data',
            name='Persone',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.user'),
        ),
    ]
