# Generated by Django 5.0 on 2023-12-23 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0006_alter_mesured_place_persone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesured_place',
            old_name='Persone',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='mesurement_data',
            old_name='Persone',
            new_name='Person',
        ),
        migrations.AlterField(
            model_name='mesurement_data',
            name='Place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.mesured_place'),
        ),
        migrations.AlterField(
            model_name='mesurement_data',
            name='Start_Time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
