# Generated by Django 5.0 on 2023-12-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0007_rename_persone_mesured_place_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurement_data',
            name='Place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.mesured_place'),
        ),
    ]
