# Generated by Django 5.0 on 2023-12-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0013_mesurement_data_sum_mesurement_data_mesured_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_mesurement',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
