# Generated by Django 5.0 on 2023-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0015_alter_mesurement_data_sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('File', models.FileField(upload_to=None)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=None)),
            ],
        ),
    ]
