# Generated by Django 5.0 on 2023-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0016_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='File_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
