# Generated by Django 5.0 on 2023-12-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0018_remove_archive_file_location_alter_archive_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='File',
        ),
        migrations.AddField(
            model_name='archive',
            name='File_Location',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
