# Generated by Django 5.0 on 2023-12-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0019_remove_archive_file_archive_file_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurement_data',
            name='Place',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.mesured_place'),
        ),
    ]
