# Generated by Django 5.0 on 2023-12-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0022_alter_mesured_place_person_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all_mesurement',
            new_name='all_measurement',
        ),
        migrations.RenameModel(
            old_name='mesured_place',
            new_name='measured_place',
        ),
        migrations.RenameModel(
            old_name='mesurement_data',
            new_name='measurement_data',
        ),
        migrations.RenameModel(
            old_name='mesurement_list',
            new_name='measurement_list',
        ),
        migrations.RenameField(
            model_name='measurement_data',
            old_name='mesured_time',
            new_name='measured_time',
        ),
    ]
