# Generated by Django 5.0 on 2023-12-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0023_rename_all_mesurement_all_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement_data',
            name='MSammount',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
