# Generated by Django 5.0 on 2023-12-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0024_measurement_data_msammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_place',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='measurement_list',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
